import { AssessmentResult, BigFiveResult, GardnerResult, KolbResult, RiasecResult } from './assessments';

export interface DemoStudent {
  name: string;
  description: { cs: string; en: string };
  results: {
    growthMindset: AssessmentResult;
    grit: AssessmentResult;
    selfEfficacy: AssessmentResult;
    testAnxiety: AssessmentResult;
    metacognition: AssessmentResult;
    eq: AssessmentResult;
    procrastination: AssessmentResult;
    academicMotivation: AssessmentResult;
    timeManagement: AssessmentResult;
    locusOfControl: AssessmentResult;
    resilience: AssessmentResult;
    studyStress: AssessmentResult;
    studyStrategies: AssessmentResult;
    bigFive: BigFiveResult;
    vak: { visual: number; auditory: number; kinesthetic: number; label: string };
  };
}

// Helper to create an AssessmentResult from a percent value
function ar(percent: number, label: { cs: string; en: string }, description: { cs: string; en: string }, tips: { cs: string[]; en: string[] }): AssessmentResult {
  const maxScore = 32;
  const score = Math.round((percent / 100) * maxScore);
  return { score, maxScore, percent, label, description, tips };
}

export const demoStudents: DemoStudent[] = [
  // ──────────────────────────────────────────────
  // 1. Petra Nováková – Excellent all-rounder
  // ──────────────────────────────────────────────
  {
    name: 'Petra Nováková',
    description: {
      cs: 'Výborná studentka se silným růstovým myšlením a vynikajícími studijními návyky.',
      en: 'Excellent student with strong growth mindset and outstanding study habits.',
    },
    results: {
      growthMindset: ar(91, { cs: 'Silné růstové myšlení', en: 'Strong Growth Mindset' },
        { cs: 'Věříš, že schopnosti lze rozvíjet úsilím a učením.', en: 'You believe abilities can be developed through effort and learning.' },
        { cs: ['Pokračuj v přijímání výzev', 'Pomáhej ostatním rozvíjet růstové myšlení', 'Sdílej své strategie učení'], en: ['Continue embracing challenges', 'Help others develop growth mindset', 'Share your learning strategies'] }),
      grit: ar(88, { cs: 'Vysoká vytrvalost (Grit)', en: 'High Grit' },
        { cs: 'Máš silnou vytrvalost a schopnost dotahovat věci do konce.', en: 'You have strong perseverance and ability to see things through.' },
        { cs: ['Využij svou vytrvalost pro náročné dlouhodobé cíle', 'Pomáhej ostatním s motivací', 'Hledej mentory pro další růst'], en: ['Use your grit for challenging long-term goals', 'Help others with motivation', 'Seek mentors for further growth'] }),
      selfEfficacy: ar(84, { cs: 'Vysoká self-efficacy', en: 'High Self-Efficacy' },
        { cs: 'Silně věříš ve své schopnosti a zvládání výzev.', en: 'You strongly believe in your abilities and handling challenges.' },
        { cs: ['Přijímej náročnější výzvy', 'Buď mentorem pro ostatní', 'Stanovuj si ambiciózní cíle'], en: ['Take on more challenging goals', 'Be a mentor to others', 'Set ambitious goals'] }),
      testAnxiety: ar(81, { cs: 'Nízká testová úzkost', en: 'Low Test Anxiety' },
        { cs: 'Zkoušky tě příliš nestresují.', en: 'Exams don\'t stress you much.' },
        { cs: ['Udržuj zdravé návyky', 'Pomáhej spolužákům se zvládáním stresu', 'Využij svůj klid pro náročnější výzvy'], en: ['Maintain healthy habits', 'Help classmates manage stress', 'Use your calm for bigger challenges'] }),
      metacognition: ar(88, { cs: 'Vysoká metakognice', en: 'High Metacognition' },
        { cs: 'Dobře znáš své myšlení a umíš se efektivně učit.', en: 'You know your thinking well and learn effectively.' },
        { cs: ['Sdílej své strategie s ostatními', 'Zkoušej pokročilé techniky učení', 'Pomáhej spolužákům'], en: ['Share your strategies with others', 'Try advanced learning techniques', 'Help classmates'] }),
      eq: ar(81, { cs: 'Vysoká emoční inteligence', en: 'High Emotional Intelligence' },
        { cs: 'Výborně rozumíš svým i cizím emocím a dokážeš je regulovat.', en: 'You understand your own and others\' emotions well and can regulate them.' },
        { cs: ['Využij svou EQ pro leadership', 'Pomáhej budovat pozitivní klima v týmu', 'Rozvíjej emoční koučování ostatních'], en: ['Use your EQ for leadership', 'Help build positive team climate', 'Develop emotional coaching of others'] }),
      procrastination: ar(84, { cs: 'Nízká prokrastinace', en: 'Low Procrastination' },
        { cs: 'Málokdy odkládáš úkoly a máš dobré pracovní návyky.', en: 'You rarely put off tasks and have good work habits.' },
        { cs: ['Udržuj své návyky', 'Pomáhej ostatním s organizací', 'Využij volný čas pro rozvoj'], en: ['Maintain your habits', 'Help others with organization', 'Use free time for growth'] }),
      academicMotivation: ar(88, { cs: 'Silná vnitřní motivace', en: 'Strong Intrinsic Motivation' },
        { cs: 'Studuješ hlavně proto, že tě to baví a chceš se rozvíjet.', en: 'You study mainly because you enjoy it and want to develop.' },
        { cs: ['Hledej náročnější výzvy', 'Zapoj se do výzkumu nebo projektů', 'Sdílej své nadšení s ostatními'], en: ['Seek more challenging projects', 'Get involved in research or projects', 'Share your enthusiasm with others'] }),
      timeManagement: ar(84, { cs: 'Výborný time management', en: 'Excellent Time Management' },
        { cs: 'Výborně si organizuješ čas a plníš termíny.', en: 'You organize your time excellently and meet deadlines.' },
        { cs: ['Zkus pokročilé techniky jako time blocking', 'Pomáhej ostatním s plánováním', 'Optimalizuj své rutiny'], en: ['Try advanced techniques like time blocking', 'Help others with planning', 'Optimize your routines'] }),
      locusOfControl: ar(91, { cs: 'Silný interní locus of control', en: 'Strong Internal Locus of Control' },
        { cs: 'Věříš, že tvé výsledky závisí hlavně na tvém úsilí.', en: 'You believe your results depend mainly on your effort.' },
        { cs: ['Využij svou zodpovědnost pro větší cíle', 'Inspiruj ostatní svým přístupem', 'Hledej oblasti, kde můžeš mít ještě větší vliv'], en: ['Use your responsibility for bigger goals', 'Inspire others with your approach', 'Find areas where you can have even greater impact'] }),
      resilience: ar(84, { cs: 'Vysoká resilience', en: 'High Resilience' },
        { cs: 'Dokážeš se rychle vzpamatovat z neúspěchů a adaptovat se.', en: 'You can quickly recover from setbacks and adapt.' },
        { cs: ['Pomáhej ostatním budovat odolnost', 'Přijímej větší výzvy', 'Sdílej své copingové strategie'], en: ['Help others build resilience', 'Take on bigger challenges', 'Share your coping strategies'] }),
      studyStress: ar(78, { cs: 'Nízký studijní stres', en: 'Low Study Stress' },
        { cs: 'Studium tě příliš nestresuje a máš dobré copingové strategie.', en: 'Studies don\'t stress you much and you have good coping strategies.' },
        { cs: ['Udržuj své zdravé návyky', 'Pomáhej spolužákům se zvládáním stresu', 'Využij svůj klid pro náročnější výzvy'], en: ['Maintain your healthy habits', 'Help classmates manage stress', 'Use your calm for bigger challenges'] }),
      studyStrategies: ar(88, { cs: 'Pokročilé studijní strategie', en: 'Advanced Study Strategies' },
        { cs: 'Používáš evidence-based techniky učení. Tvůj přístup je vědecky efektivní.', en: 'You use evidence-based learning techniques. Your approach is scientifically effective.' },
        { cs: ['Zkus interleaving – střídej témata při učení', 'Sdílej strategie se spolužáky', 'Experimentuj s elaborative interrogation'], en: ['Try interleaving – alternate topics while studying', 'Share strategies with classmates', 'Experiment with elaborative interrogation'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 6, percent: 75, description: { cs: 'Jsi společenský/á a energický/á v sociálních situacích.', en: 'You are sociable and energetic in social situations.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 7, percent: 88, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 8, percent: 100, description: { cs: 'Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'You are organized, reliable, and goal-oriented.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 7, percent: 88, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 7, percent: 88, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Svědomitost. Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'Your most prominent trait is Conscientiousness. You are organized, reliable, and goal-oriented.' },
      },
      vak: { visual: 45, auditory: 30, kinesthetic: 25, label: 'Vizuální preference' },
    },
  },

  // ──────────────────────────────────────────────
  // 2. Tomáš Dvořák – Struggling student
  // ──────────────────────────────────────────────
  {
    name: 'Tomáš Dvořák',
    description: {
      cs: 'Student s nízkou motivací, vysokou prokrastinací a značným stresem ze studia.',
      en: 'Student with low motivation, high procrastination, and significant study stress.',
    },
    results: {
      growthMindset: ar(25, { cs: 'Smíšené myšlení', en: 'Mixed Mindset' },
        { cs: 'Střídáš mezi fixním a růstovým pohledem.', en: 'You alternate between fixed and growth perspectives.' },
        { cs: ['Zaměř se na učení z chyb', 'Hledej inspiraci v příbězích úspěšných lidí', 'Experimentuj s novými přístupy'], en: ['Focus on learning from mistakes', 'Find inspiration in success stories', 'Experiment with new approaches'] }),
      grit: ar(22, { cs: 'Nízká vytrvalost', en: 'Low Perseverance' },
        { cs: 'Často měníš cíle a zájmy.', en: 'You often change goals and interests.' },
        { cs: ['Zaměř se na jeden cíl', 'Vytvoř si rutiny', 'Najdi důvod PROČ'], en: ['Focus on one goal', 'Create routines', 'Find your WHY'] }),
      selfEfficacy: ar(28, { cs: 'Střední self-efficacy', en: 'Moderate Self-Efficacy' },
        { cs: 'Občas pochybuješ o svých schopnostech.', en: 'You sometimes doubt your abilities.' },
        { cs: ['Začni s menšími úkoly a postupně zvyšuj', 'Najdi vzory, které tě inspirují', 'Pracuj na pozitivním self-talku'], en: ['Start with smaller tasks and gradually increase', 'Find role models who inspire you', 'Work on positive self-talk'] }),
      testAnxiety: ar(28, { cs: 'Vyšší testová úzkost', en: 'Moderate Test Anxiety' },
        { cs: 'Zkoušky ti působí značný stres.', en: 'Exams cause you significant stress.' },
        { cs: ['Praktikuj mindfulness', 'Vytvoř si relaxační rutinu', 'Mluv o svých obavách s někým blízkým'], en: ['Practice mindfulness', 'Create a relaxation routine', 'Talk about your worries with someone close'] }),
      metacognition: ar(25, { cs: 'Rozvíjející se metakognice', en: 'Developing Metacognition' },
        { cs: 'Začínáš si uvědomovat důležitost plánování učení.', en: 'You\'re beginning to realize the importance of planning your learning.' },
        { cs: ['Před učením si napiš 3 otázky, na které chceš znát odpověď', 'Po učení si řekni nahlas, co sis zapamatoval/a', 'Zkus Pomodoro techniku'], en: ['Before studying, write 3 questions you want answered', 'After studying, say aloud what you remember', 'Try the Pomodoro technique'] }),
      eq: ar(34, { cs: 'Rozvíjející se EQ', en: 'Developing EQ' },
        { cs: 'Emoce občas ovlivňují tvé rozhodování a vztahy.', en: 'Emotions sometimes affect your decision-making and relationships.' },
        { cs: ['Zkus pojmenovávat své emoce', 'Nauč se techniku STOP (zastav se, nadechni, pozoruj, pokračuj)', 'Veď si emoční deník'], en: ['Try naming your emotions', 'Learn the STOP technique (stop, breathe, observe, proceed)', 'Keep an emotional journal'] }),
      procrastination: ar(19, { cs: 'Vysoká prokrastinace', en: 'High Procrastination' },
        { cs: 'Často odkládáš úkoly a učení na poslední chvíli.', en: 'You often put off tasks and studying until the last minute.' },
        { cs: ['Začni pravidlem 2 minut – udělej aspoň začátek', 'Odstraň rozptýlení (telefon do jiné místnosti)', 'Najdi si accountability partnera'], en: ['Start with the 2-minute rule – just begin', 'Remove distractions (phone in another room)', 'Find an accountability partner'] }),
      academicMotivation: ar(22, { cs: 'Nízká motivace (amotivace)', en: 'Low Motivation (Amotivation)' },
        { cs: 'Nevíš, proč vlastně studuješ, a chybí ti smysl.', en: 'You don\'t know why you\'re studying and lack a sense of purpose.' },
        { cs: ['Zamysli se, co tě baví mimo školu', 'Promluvte si s kariérním poradcem', 'Zkus najít alespoň jeden předmět, který tě zajímá'], en: ['Think about what you enjoy outside school', 'Talk to a career advisor', 'Try to find at least one subject that interests you'] }),
      timeManagement: ar(19, { cs: 'Kritický time management', en: 'Critical Time Management' },
        { cs: 'Nemáš systém organizace času a často nestíháš.', en: 'You have no time organization system and often miss deadlines.' },
        { cs: ['Začni s jedním jednoduchým plánovačem', 'Nastav si připomínky na termíny', 'Každý večer naplánuj 3 úkoly na další den'], en: ['Start with one simple planner', 'Set reminders for deadlines', 'Each evening plan 3 tasks for the next day'] }),
      locusOfControl: ar(25, { cs: 'Smíšený locus of control', en: 'Mixed Locus of Control' },
        { cs: 'Někdy věříš ve svůj vliv, jindy máš pocit, že vše závisí na okolnostech.', en: 'Sometimes you believe in your influence, other times you feel everything depends on circumstances.' },
        { cs: ['Zaměř se na věci, které můžeš ovlivnit', 'Veď si deník úspěchů', 'Analyzuj, co vedlo k tvým úspěchům'], en: ['Focus on things you can control', 'Keep a success journal', 'Analyze what led to your successes'] }),
      resilience: ar(25, { cs: 'Nižší resilience', en: 'Lower Resilience' },
        { cs: 'Neúspěchy tě silně zasáhnou a těžko se z nich vzpamatováváš.', en: 'Setbacks hit you hard and you struggle to recover.' },
        { cs: ['Mluv o problémech s někým blízkým', 'Zaměř se na malé denní úspěchy', 'Zkus techniku přerámování – co se z toho můžeš naučit?'], en: ['Talk about problems with someone close', 'Focus on small daily wins', 'Try reframing – what can you learn from this?'] }),
      studyStress: ar(22, { cs: 'Vyšší studijní stres', en: 'High Study Stress' },
        { cs: 'Studium ti působí značný stres, který ovlivňuje tvé zdraví.', en: 'Studies cause you significant stress affecting your health.' },
        { cs: ['Vyhledej podporu (studijní poradce, psycholog)', 'Zkus techniku 4-7-8 dýchání před spaním', 'Rozděl zkoušky do menších bloků přípravy'], en: ['Seek support (study advisor, psychologist)', 'Try 4-7-8 breathing technique before sleep', 'Break exam prep into smaller blocks'] }),
      studyStrategies: ar(22, { cs: 'Neefektivní studijní strategie', en: 'Ineffective Study Strategies' },
        { cs: 'Nemáš funkční systém učení. To je ale příležitost – správné techniky mohou zásadně změnit tvé výsledky.', en: 'You don\'t have a functional study system. But that\'s an opportunity – the right techniques can fundamentally change your results.' },
        { cs: ['Začni s jednou technikou: po učení zavři knihu a řekni nahlas, co si pamatuješ', 'Stáhni si Anki a vytvoř si kartičky z přednášek', 'Sleduj „Learning How to Learn" kurz na Coursera (zdarma)'], en: ['Start with one technique: close the book and say aloud what you remember', 'Download Anki and create flashcards from lectures', 'Watch "Learning How to Learn" course on Coursera (free)'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 4, percent: 50, description: { cs: 'Jsi společenský/á a energický/á v sociálních situacích.', en: 'You are sociable and energetic in social situations.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 4, percent: 50, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 2, percent: 25, description: { cs: 'Jsi flexibilní a spontánní, ale možná méně organizovaný/á.', en: 'You are flexible and spontaneous, but perhaps less organized.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 3, percent: 38, description: { cs: 'Jsi citlivý/á a emoce prožíváš intenzivně.', en: 'You are sensitive and experience emotions intensely.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 3, percent: 38, description: { cs: 'Jsi praktický/á a preferuješ osvědčené postupy.', en: 'You are practical and prefer proven approaches.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Extraverze. Jsi společenský/á a energický/á v sociálních situacích.', en: 'Your most prominent trait is Extraversion. You are sociable and energetic in social situations.' },
      },
      vak: { visual: 30, auditory: 35, kinesthetic: 35, label: 'Auditivní-Kinestetický mix' },
    },
  },

  // ──────────────────────────────────────────────
  // 3. Karolína Marková – Creative type
  // ──────────────────────────────────────────────
  {
    name: 'Karolína Marková',
    description: {
      cs: 'Kreativní studentka s vysokou otevřeností, ale slabším time managementem.',
      en: 'Creative student with high openness but weaker time management.',
    },
    results: {
      growthMindset: ar(72, { cs: 'Převážně růstové myšlení', en: 'Mostly Growth Mindset' },
        { cs: 'Většinou věříš v možnost rozvoje, ale někdy pochybuješ.', en: 'You mostly believe in development potential, but sometimes doubt.' },
        { cs: ['Všímej si svých fixních myšlenek', 'Přeformuluj "neumím to" na "zatím neumím"', 'Oceňuj proces, ne jen výsledek'], en: ['Notice your fixed mindset thoughts', 'Reframe "I can\'t" to "I can\'t yet"', 'Value the process, not just results'] }),
      grit: ar(56, { cs: 'Dobrá vytrvalost', en: 'Good Perseverance' },
        { cs: 'Většinou dokážeš vytrvat, ale někdy se necháš odvést.', en: 'You can usually persevere, but sometimes get sidetracked.' },
        { cs: ['Rozděluj velké cíle na menší kroky', 'Najdi si accountability partnera', 'Slaví malé úspěchy'], en: ['Break big goals into smaller steps', 'Find an accountability partner', 'Celebrate small wins'] }),
      selfEfficacy: ar(66, { cs: 'Dobrá self-efficacy', en: 'Good Self-Efficacy' },
        { cs: 'Věříš si ve většině situací.', en: 'You believe in yourself in most situations.' },
        { cs: ['Zaznamenávej své úspěchy', 'Vizualizuj úspěšné zvládnutí úkolů', 'Hledej pozitivní zpětnou vazbu'], en: ['Record your successes', 'Visualize successful task completion', 'Seek positive feedback'] }),
      testAnxiety: ar(59, { cs: 'Mírná testová úzkost', en: 'Mild Test Anxiety' },
        { cs: 'Občas cítíš stres před zkouškami.', en: 'You sometimes feel stressed before exams.' },
        { cs: ['Nauč se dechová cvičení', 'Připravuj se s dostatečným předstihem', 'Vyzkoušej progresivní svalovou relaxaci'], en: ['Learn breathing exercises', 'Prepare well in advance', 'Try progressive muscle relaxation'] }),
      metacognition: ar(63, { cs: 'Dobrá metakognice', en: 'Good Metacognition' },
        { cs: 'Většinou si uvědomuješ své učení.', en: 'You\'re usually aware of your learning.' },
        { cs: ['Veď si učební deník', 'Experimentuj s novými technikami', 'Ptej se sám sebe "proč?"'], en: ['Keep a learning journal', 'Experiment with new techniques', 'Ask yourself "why?"'] }),
      eq: ar(69, { cs: 'Dobrá emoční inteligence', en: 'Good Emotional Intelligence' },
        { cs: 'Většinou rozumíš emocím a dokážeš je zvládat.', en: 'You usually understand emotions and can manage them.' },
        { cs: ['Rozvíjej aktivní naslouchání', 'Praktikuj empatii v každodenních situacích', 'Nauč se rozpoznávat emoce u druhých'], en: ['Develop active listening', 'Practice empathy in daily situations', 'Learn to recognize emotions in others'] }),
      procrastination: ar(50, { cs: 'Mírná prokrastinace', en: 'Mild Procrastination' },
        { cs: 'Občas odkládáš úkoly, ale většinou je zvládneš včas.', en: 'You sometimes put off tasks, but usually manage them on time.' },
        { cs: ['Začni s nejtěžším úkolem ráno', 'Používej techniku „eat the frog"', 'Nastav si krátké deadliny pro dílčí kroky'], en: ['Start with the hardest task in the morning', 'Use the "eat the frog" technique', 'Set short deadlines for sub-tasks'] }),
      academicMotivation: ar(69, { cs: 'Smíšená motivace', en: 'Mixed Motivation' },
        { cs: 'Motivace závisí na předmětu – některé tě baví, jiné ne.', en: 'Your motivation depends on the subject – you enjoy some, not others.' },
        { cs: ['Hledej propojení mezi předměty a svými zájmy', 'Zkus kreativní přístup i k nudným předmětům', 'Stanovi si osobní cíle pro každý předmět'], en: ['Find connections between subjects and your interests', 'Try a creative approach even for boring subjects', 'Set personal goals for each subject'] }),
      timeManagement: ar(41, { cs: 'Slabší time management', en: 'Weak Time Management' },
        { cs: 'Máš potíže s organizací času a plánováním.', en: 'You have trouble organizing your time and planning.' },
        { cs: ['Zkus si plánovat týden dopředu', 'Používej kalendář pro všechny termíny', 'Nastav si pevné studijní bloky'], en: ['Try planning a week ahead', 'Use a calendar for all deadlines', 'Set fixed study blocks'] }),
      locusOfControl: ar(63, { cs: 'Převážně interní locus', en: 'Mostly Internal Locus' },
        { cs: 'Většinou věříš, že máš vliv na své výsledky.', en: 'You mostly believe you have influence over your results.' },
        { cs: ['Posiluj přesvědčení, že tvé úsilí se vyplatí', 'Analyzuj své úspěchy – co jsi udělal/a správně?', 'Přijmi zodpovědnost za své výsledky'], en: ['Strengthen the belief that your effort pays off', 'Analyze your successes – what did you do right?', 'Accept responsibility for your results'] }),
      resilience: ar(63, { cs: 'Dobrá resilience', en: 'Good Resilience' },
        { cs: 'Většinou se dokážeš vzpamatovat z neúspěchů.', en: 'You can usually recover from setbacks.' },
        { cs: ['Buduj síť podpory', 'Praktikuj vděčnost', 'Hledej příležitosti v překážkách'], en: ['Build a support network', 'Practice gratitude', 'Look for opportunities in obstacles'] }),
      studyStress: ar(56, { cs: 'Mírný studijní stres', en: 'Moderate Study Stress' },
        { cs: 'Občas cítíš stres, ale většinou ho zvládáš.', en: 'You sometimes feel stressed but usually manage it.' },
        { cs: ['Zaveď pravidelný pohyb (i 20 min denně pomůže)', 'Plánuj studium s přestávkami', 'Nauč se říkat ne nepodstatným aktivitám'], en: ['Start regular exercise (even 20 min daily helps)', 'Plan study sessions with breaks', 'Learn to say no to non-essential activities'] }),
      studyStrategies: ar(59, { cs: 'Dobré studijní strategie', en: 'Good Study Strategies' },
        { cs: 'Máš solidní základ, ale je prostor pro zlepšení.', en: 'You have a solid foundation but room for improvement.' },
        { cs: ['Přidej active recall – testuj se místo opakovaného čtení', 'Zkus Pomodoro techniku (25 min práce, 5 min pauza)', 'Používej Anki nebo Quizlet pro spaced repetition'], en: ['Add active recall – test yourself instead of re-reading', 'Try Pomodoro technique (25 min work, 5 min break)', 'Use Anki or Quizlet for spaced repetition'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 5, percent: 63, description: { cs: 'Jsi společenský/á a energický/á v sociálních situacích.', en: 'You are sociable and energetic in social situations.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 6, percent: 75, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 3, percent: 38, description: { cs: 'Jsi flexibilní a spontánní, ale možná méně organizovaný/á.', en: 'You are flexible and spontaneous, but perhaps less organized.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 5, percent: 63, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 8, percent: 100, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Otevřenost zkušenosti. Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'Your most prominent trait is Openness to Experience. You are creative, curious, and open to new things.' },
      },
      vak: { visual: 50, auditory: 20, kinesthetic: 30, label: 'Vizuální preference' },
    },
  },

  // ──────────────────────────────────────────────
  // 4. Jakub Černý – STEM achiever
  // ──────────────────────────────────────────────
  {
    name: 'Jakub Černý',
    description: {
      cs: 'Analyticky orientovaný student s vysokou metakognicí, ale nižší emoční inteligencí.',
      en: 'Analytically oriented student with high metacognition but lower emotional intelligence.',
    },
    results: {
      growthMindset: ar(78, { cs: 'Silné růstové myšlení', en: 'Strong Growth Mindset' },
        { cs: 'Věříš, že schopnosti lze rozvíjet úsilím a učením.', en: 'You believe abilities can be developed through effort and learning.' },
        { cs: ['Pokračuj v přijímání výzev', 'Pomáhej ostatním rozvíjet růstové myšlení', 'Sdílej své strategie učení'], en: ['Continue embracing challenges', 'Help others develop growth mindset', 'Share your learning strategies'] }),
      grit: ar(75, { cs: 'Vysoká vytrvalost (Grit)', en: 'High Grit' },
        { cs: 'Máš silnou vytrvalost a schopnost dotahovat věci do konce.', en: 'You have strong perseverance and ability to see things through.' },
        { cs: ['Využij svou vytrvalost pro náročné dlouhodobé cíle', 'Pomáhej ostatním s motivací', 'Hledej mentory pro další růst'], en: ['Use your grit for challenging long-term goals', 'Help others with motivation', 'Seek mentors for further growth'] }),
      selfEfficacy: ar(81, { cs: 'Vysoká self-efficacy', en: 'High Self-Efficacy' },
        { cs: 'Silně věříš ve své schopnosti a zvládání výzev.', en: 'You strongly believe in your abilities and handling challenges.' },
        { cs: ['Přijímej náročnější výzvy', 'Buď mentorem pro ostatní', 'Stanovuj si ambiciózní cíle'], en: ['Take on more challenging goals', 'Be a mentor to others', 'Set ambitious goals'] }),
      testAnxiety: ar(75, { cs: 'Nízká testová úzkost', en: 'Low Test Anxiety' },
        { cs: 'Zkoušky tě příliš nestresují.', en: 'Exams don\'t stress you much.' },
        { cs: ['Udržuj zdravé návyky', 'Pomáhej spolužákům se zvládáním stresu', 'Využij svůj klid pro náročnější výzvy'], en: ['Maintain healthy habits', 'Help classmates manage stress', 'Use your calm for bigger challenges'] }),
      metacognition: ar(84, { cs: 'Vysoká metakognice', en: 'High Metacognition' },
        { cs: 'Dobře znáš své myšlení a umíš se efektivně učit.', en: 'You know your thinking well and learn effectively.' },
        { cs: ['Sdílej své strategie s ostatními', 'Zkoušej pokročilé techniky učení', 'Pomáhej spolužákům'], en: ['Share your strategies with others', 'Try advanced learning techniques', 'Help classmates'] }),
      eq: ar(34, { cs: 'Rozvíjející se EQ', en: 'Developing EQ' },
        { cs: 'Emoce občas ovlivňují tvé rozhodování a vztahy.', en: 'Emotions sometimes affect your decision-making and relationships.' },
        { cs: ['Zkus pojmenovávat své emoce', 'Nauč se techniku STOP (zastav se, nadechni, pozoruj, pokračuj)', 'Veď si emoční deník'], en: ['Try naming your emotions', 'Learn the STOP technique (stop, breathe, observe, proceed)', 'Keep an emotional journal'] }),
      procrastination: ar(72, { cs: 'Nízká prokrastinace', en: 'Low Procrastination' },
        { cs: 'Málokdy odkládáš úkoly a máš dobré pracovní návyky.', en: 'You rarely put off tasks and have good work habits.' },
        { cs: ['Udržuj své návyky', 'Pomáhej ostatním s organizací', 'Využij volný čas pro rozvoj'], en: ['Maintain your habits', 'Help others with organization', 'Use free time for growth'] }),
      academicMotivation: ar(75, { cs: 'Silná vnitřní motivace', en: 'Strong Intrinsic Motivation' },
        { cs: 'Studuješ hlavně proto, že tě to baví a chceš se rozvíjet.', en: 'You study mainly because you enjoy it and want to develop.' },
        { cs: ['Hledej náročnější výzvy', 'Zapoj se do výzkumu nebo projektů', 'Sdílej své nadšení s ostatními'], en: ['Seek more challenging projects', 'Get involved in research or projects', 'Share your enthusiasm with others'] }),
      timeManagement: ar(72, { cs: 'Dobrý time management', en: 'Good Time Management' },
        { cs: 'Většinou si dobře organizuješ čas.', en: 'You usually organize your time well.' },
        { cs: ['Zkus Pomodoro techniku', 'Optimalizuj své ranní rutiny', 'Plánuj s ohledem na svou energii'], en: ['Try the Pomodoro technique', 'Optimize your morning routines', 'Plan according to your energy levels'] }),
      locusOfControl: ar(81, { cs: 'Silný interní locus of control', en: 'Strong Internal Locus of Control' },
        { cs: 'Věříš, že tvé výsledky závisí hlavně na tvém úsilí.', en: 'You believe your results depend mainly on your effort.' },
        { cs: ['Využij svou zodpovědnost pro větší cíle', 'Inspiruj ostatní svým přístupem', 'Hledej oblasti, kde můžeš mít ještě větší vliv'], en: ['Use your responsibility for bigger goals', 'Inspire others with your approach', 'Find areas where you can have even greater impact'] }),
      resilience: ar(69, { cs: 'Dobrá resilience', en: 'Good Resilience' },
        { cs: 'Většinou se dokážeš vzpamatovat z neúspěchů.', en: 'You can usually recover from setbacks.' },
        { cs: ['Buduj síť podpory', 'Praktikuj vděčnost', 'Hledej příležitosti v překážkách'], en: ['Build a support network', 'Practice gratitude', 'Look for opportunities in obstacles'] }),
      studyStress: ar(69, { cs: 'Mírný studijní stres', en: 'Moderate Study Stress' },
        { cs: 'Občas cítíš stres, ale většinou ho zvládáš.', en: 'You sometimes feel stressed but usually manage it.' },
        { cs: ['Zaveď pravidelný pohyb (i 20 min denně pomůže)', 'Plánuj studium s přestávkami', 'Nauč se říkat ne nepodstatným aktivitám'], en: ['Start regular exercise (even 20 min daily helps)', 'Plan study sessions with breaks', 'Learn to say no to non-essential activities'] }),
      studyStrategies: ar(81, { cs: 'Pokročilé studijní strategie', en: 'Advanced Study Strategies' },
        { cs: 'Používáš evidence-based techniky učení. Tvůj přístup je vědecky efektivní.', en: 'You use evidence-based learning techniques. Your approach is scientifically effective.' },
        { cs: ['Zkus interleaving – střídej témata při učení', 'Sdílej strategie se spolužáky', 'Experimentuj s elaborative interrogation'], en: ['Try interleaving – alternate topics while studying', 'Share strategies with classmates', 'Experiment with elaborative interrogation'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 3, percent: 38, description: { cs: 'Preferuješ klid a samostatnou práci.', en: 'You prefer quiet and independent work.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 3, percent: 38, description: { cs: 'Jsi analytický/á a zaměřený/á na fakta více než na pocity.', en: 'You are analytical and focused on facts rather than feelings.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 7, percent: 88, description: { cs: 'Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'You are organized, reliable, and goal-oriented.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 6, percent: 75, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 5, percent: 63, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Svědomitost. Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'Your most prominent trait is Conscientiousness. You are organized, reliable, and goal-oriented.' },
      },
      vak: { visual: 55, auditory: 30, kinesthetic: 15, label: 'Vizuální preference' },
    },
  },

  // ──────────────────────────────────────────────
  // 5. Anna Svobodová – Social butterfly
  // ──────────────────────────────────────────────
  {
    name: 'Anna Svobodová',
    description: {
      cs: 'Společenská studentka s vysokou emoční inteligencí, ale nižší vytrvalostí.',
      en: 'Sociable student with high emotional intelligence but lower perseverance.',
    },
    results: {
      growthMindset: ar(63, { cs: 'Převážně růstové myšlení', en: 'Mostly Growth Mindset' },
        { cs: 'Většinou věříš v možnost rozvoje, ale někdy pochybuješ.', en: 'You mostly believe in development potential, but sometimes doubt.' },
        { cs: ['Všímej si svých fixních myšlenek', 'Přeformuluj "neumím to" na "zatím neumím"', 'Oceňuj proces, ne jen výsledek'], en: ['Notice your fixed mindset thoughts', 'Reframe "I can\'t" to "I can\'t yet"', 'Value the process, not just results'] }),
      grit: ar(44, { cs: 'Rozvíjející se vytrvalost', en: 'Developing Perseverance' },
        { cs: 'Máš tendenci měnit směr, ale můžeš to zlepšit.', en: 'You tend to change direction, but you can improve.' },
        { cs: ['Začni s kratšími projekty', 'Veď si deník pokroku', 'Najdi svou vášeň'], en: ['Start with shorter projects', 'Keep a progress journal', 'Find your passion'] }),
      selfEfficacy: ar(59, { cs: 'Dobrá self-efficacy', en: 'Good Self-Efficacy' },
        { cs: 'Věříš si ve většině situací.', en: 'You believe in yourself in most situations.' },
        { cs: ['Zaznamenávej své úspěchy', 'Vizualizuj úspěšné zvládnutí úkolů', 'Hledej pozitivní zpětnou vazbu'], en: ['Record your successes', 'Visualize successful task completion', 'Seek positive feedback'] }),
      testAnxiety: ar(56, { cs: 'Mírná testová úzkost', en: 'Mild Test Anxiety' },
        { cs: 'Občas cítíš stres před zkouškami.', en: 'You sometimes feel stressed before exams.' },
        { cs: ['Nauč se dechová cvičení', 'Připravuj se s dostatečným předstihem', 'Vyzkoušej progresivní svalovou relaxaci'], en: ['Learn breathing exercises', 'Prepare well in advance', 'Try progressive muscle relaxation'] }),
      metacognition: ar(53, { cs: 'Dobrá metakognice', en: 'Good Metacognition' },
        { cs: 'Většinou si uvědomuješ své učení.', en: 'You\'re usually aware of your learning.' },
        { cs: ['Veď si učební deník', 'Experimentuj s novými technikami', 'Ptej se sám sebe "proč?"'], en: ['Keep a learning journal', 'Experiment with new techniques', 'Ask yourself "why?"'] }),
      eq: ar(88, { cs: 'Vysoká emoční inteligence', en: 'High Emotional Intelligence' },
        { cs: 'Výborně rozumíš svým i cizím emocím a dokážeš je regulovat.', en: 'You understand your own and others\' emotions well and can regulate them.' },
        { cs: ['Využij svou EQ pro leadership', 'Pomáhej budovat pozitivní klima v týmu', 'Rozvíjej emoční koučování ostatních'], en: ['Use your EQ for leadership', 'Help build positive team climate', 'Develop emotional coaching of others'] }),
      procrastination: ar(50, { cs: 'Mírná prokrastinace', en: 'Mild Procrastination' },
        { cs: 'Občas odkládáš úkoly, ale většinou je zvládneš včas.', en: 'You sometimes put off tasks, but usually manage them on time.' },
        { cs: ['Začni s nejtěžším úkolem ráno', 'Používej techniku „eat the frog"', 'Nastav si krátké deadliny pro dílčí kroky'], en: ['Start with the hardest task in the morning', 'Use the "eat the frog" technique', 'Set short deadlines for sub-tasks'] }),
      academicMotivation: ar(56, { cs: 'Smíšená motivace', en: 'Mixed Motivation' },
        { cs: 'Motivace závisí na předmětu – některé tě baví, jiné ne.', en: 'Your motivation depends on the subject – you enjoy some, not others.' },
        { cs: ['Hledej propojení mezi předměty a svými zájmy', 'Zkus kreativní přístup i k nudným předmětům', 'Stanovi si osobní cíle pro každý předmět'], en: ['Find connections between subjects and your interests', 'Try a creative approach even for boring subjects', 'Set personal goals for each subject'] }),
      timeManagement: ar(50, { cs: 'Dobrý time management', en: 'Good Time Management' },
        { cs: 'Většinou si dobře organizuješ čas.', en: 'You usually organize your time well.' },
        { cs: ['Zkus Pomodoro techniku', 'Optimalizuj své ranní rutiny', 'Plánuj s ohledem na svou energii'], en: ['Try the Pomodoro technique', 'Optimize your morning routines', 'Plan according to your energy levels'] }),
      locusOfControl: ar(56, { cs: 'Převážně interní locus', en: 'Mostly Internal Locus' },
        { cs: 'Většinou věříš, že máš vliv na své výsledky.', en: 'You mostly believe you have influence over your results.' },
        { cs: ['Posiluj přesvědčení, že tvé úsilí se vyplatí', 'Analyzuj své úspěchy – co jsi udělal/a správně?', 'Přijmi zodpovědnost za své výsledky'], en: ['Strengthen the belief that your effort pays off', 'Analyze your successes – what did you do right?', 'Accept responsibility for your results'] }),
      resilience: ar(63, { cs: 'Dobrá resilience', en: 'Good Resilience' },
        { cs: 'Většinou se dokážeš vzpamatovat z neúspěchů.', en: 'You can usually recover from setbacks.' },
        { cs: ['Buduj síť podpory', 'Praktikuj vděčnost', 'Hledej příležitosti v překážkách'], en: ['Build a support network', 'Practice gratitude', 'Look for opportunities in obstacles'] }),
      studyStress: ar(59, { cs: 'Mírný studijní stres', en: 'Moderate Study Stress' },
        { cs: 'Občas cítíš stres, ale většinou ho zvládáš.', en: 'You sometimes feel stressed but usually manage it.' },
        { cs: ['Zaveď pravidelný pohyb (i 20 min denně pomůže)', 'Plánuj studium s přestávkami', 'Nauč se říkat ne nepodstatným aktivitám'], en: ['Start regular exercise (even 20 min daily helps)', 'Plan study sessions with breaks', 'Learn to say no to non-essential activities'] }),
      studyStrategies: ar(50, { cs: 'Dobré studijní strategie', en: 'Good Study Strategies' },
        { cs: 'Máš solidní základ, ale je prostor pro zlepšení.', en: 'You have a solid foundation but room for improvement.' },
        { cs: ['Přidej active recall – testuj se místo opakovaného čtení', 'Zkus Pomodoro techniku (25 min práce, 5 min pauza)', 'Používej Anki nebo Quizlet pro spaced repetition'], en: ['Add active recall – test yourself instead of re-reading', 'Try Pomodoro technique (25 min work, 5 min break)', 'Use Anki or Quizlet for spaced repetition'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 8, percent: 100, description: { cs: 'Jsi společenský/á a energický/á v sociálních situacích.', en: 'You are sociable and energetic in social situations.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 7, percent: 88, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 4, percent: 50, description: { cs: 'Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'You are organized, reliable, and goal-oriented.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 5, percent: 63, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 6, percent: 75, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Extraverze. Jsi společenský/á a energický/á v sociálních situacích.', en: 'Your most prominent trait is Extraversion. You are sociable and energetic in social situations.' },
      },
      vak: { visual: 25, auditory: 50, kinesthetic: 25, label: 'Auditivní preference' },
    },
  },

  // ──────────────────────────────────────────────
  // 6. Martin Procházka – Anxious perfectionist
  // ──────────────────────────────────────────────
  {
    name: 'Martin Procházka',
    description: {
      cs: 'Perfekcionistický student s vysokou svědomitostí, ale silnou testovou úzkostí.',
      en: 'Perfectionist student with high conscientiousness but strong test anxiety.',
    },
    results: {
      growthMindset: ar(56, { cs: 'Převážně růstové myšlení', en: 'Mostly Growth Mindset' },
        { cs: 'Většinou věříš v možnost rozvoje, ale někdy pochybuješ.', en: 'You mostly believe in development potential, but sometimes doubt.' },
        { cs: ['Všímej si svých fixních myšlenek', 'Přeformuluj "neumím to" na "zatím neumím"', 'Oceňuj proces, ne jen výsledek'], en: ['Notice your fixed mindset thoughts', 'Reframe "I can\'t" to "I can\'t yet"', 'Value the process, not just results'] }),
      grit: ar(72, { cs: 'Dobrá vytrvalost', en: 'Good Perseverance' },
        { cs: 'Většinou dokážeš vytrvat, ale někdy se necháš odvést.', en: 'You can usually persevere, but sometimes get sidetracked.' },
        { cs: ['Rozděluj velké cíle na menší kroky', 'Najdi si accountability partnera', 'Slaví malé úspěchy'], en: ['Break big goals into smaller steps', 'Find an accountability partner', 'Celebrate small wins'] }),
      selfEfficacy: ar(47, { cs: 'Střední self-efficacy', en: 'Moderate Self-Efficacy' },
        { cs: 'Občas pochybuješ o svých schopnostech.', en: 'You sometimes doubt your abilities.' },
        { cs: ['Začni s menšími úkoly a postupně zvyšuj', 'Najdi vzory, které tě inspirují', 'Pracuj na pozitivním self-talku'], en: ['Start with smaller tasks and gradually increase', 'Find role models who inspire you', 'Work on positive self-talk'] }),
      testAnxiety: ar(25, { cs: 'Vyšší testová úzkost', en: 'Moderate Test Anxiety' },
        { cs: 'Zkoušky ti působí značný stres.', en: 'Exams cause you significant stress.' },
        { cs: ['Praktikuj mindfulness', 'Vytvoř si relaxační rutinu', 'Mluv o svých obavách s někým blízkým'], en: ['Practice mindfulness', 'Create a relaxation routine', 'Talk about your worries with someone close'] }),
      metacognition: ar(69, { cs: 'Dobrá metakognice', en: 'Good Metacognition' },
        { cs: 'Většinou si uvědomuješ své učení.', en: 'You\'re usually aware of your learning.' },
        { cs: ['Veď si učební deník', 'Experimentuj s novými technikami', 'Ptej se sám sebe "proč?"'], en: ['Keep a learning journal', 'Experiment with new techniques', 'Ask yourself "why?"'] }),
      eq: ar(53, { cs: 'Dobrá emoční inteligence', en: 'Good Emotional Intelligence' },
        { cs: 'Většinou rozumíš emocím a dokážeš je zvládat.', en: 'You usually understand emotions and can manage them.' },
        { cs: ['Rozvíjej aktivní naslouchání', 'Praktikuj empatii v každodenních situacích', 'Nauč se rozpoznávat emoce u druhých'], en: ['Develop active listening', 'Practice empathy in daily situations', 'Learn to recognize emotions in others'] }),
      procrastination: ar(63, { cs: 'Mírná prokrastinace', en: 'Mild Procrastination' },
        { cs: 'Občas odkládáš úkoly, ale většinou je zvládneš včas.', en: 'You sometimes put off tasks, but usually manage them on time.' },
        { cs: ['Začni s nejtěžším úkolem ráno', 'Používej techniku „eat the frog"', 'Nastav si krátké deadliny pro dílčí kroky'], en: ['Start with the hardest task in the morning', 'Use the "eat the frog" technique', 'Set short deadlines for sub-tasks'] }),
      academicMotivation: ar(63, { cs: 'Smíšená motivace', en: 'Mixed Motivation' },
        { cs: 'Motivace závisí na předmětu – některé tě baví, jiné ne.', en: 'Your motivation depends on the subject – you enjoy some, not others.' },
        { cs: ['Hledej propojení mezi předměty a svými zájmy', 'Zkus kreativní přístup i k nudným předmětům', 'Stanovi si osobní cíle pro každý předmět'], en: ['Find connections between subjects and your interests', 'Try a creative approach even for boring subjects', 'Set personal goals for each subject'] }),
      timeManagement: ar(75, { cs: 'Výborný time management', en: 'Excellent Time Management' },
        { cs: 'Výborně si organizuješ čas a plníš termíny.', en: 'You organize your time excellently and meet deadlines.' },
        { cs: ['Zkus pokročilé techniky jako time blocking', 'Pomáhej ostatním s plánováním', 'Optimalizuj své rutiny'], en: ['Try advanced techniques like time blocking', 'Help others with planning', 'Optimize your routines'] }),
      locusOfControl: ar(56, { cs: 'Převážně interní locus', en: 'Mostly Internal Locus' },
        { cs: 'Většinou věříš, že máš vliv na své výsledky.', en: 'You mostly believe you have influence over your results.' },
        { cs: ['Posiluj přesvědčení, že tvé úsilí se vyplatí', 'Analyzuj své úspěchy – co jsi udělal/a správně?', 'Přijmi zodpovědnost za své výsledky'], en: ['Strengthen the belief that your effort pays off', 'Analyze your successes – what did you do right?', 'Accept responsibility for your results'] }),
      resilience: ar(38, { cs: 'Nižší resilience', en: 'Lower Resilience' },
        { cs: 'Neúspěchy tě silně zasáhnou a těžko se z nich vzpamatováváš.', en: 'Setbacks hit you hard and you struggle to recover.' },
        { cs: ['Mluv o problémech s někým blízkým', 'Zaměř se na malé denní úspěchy', 'Zkus techniku přerámování – co se z toho můžeš naučit?'], en: ['Talk about problems with someone close', 'Focus on small daily wins', 'Try reframing – what can you learn from this?'] }),
      studyStress: ar(31, { cs: 'Vyšší studijní stres', en: 'High Study Stress' },
        { cs: 'Studium ti působí značný stres, který ovlivňuje tvé zdraví.', en: 'Studies cause you significant stress affecting your health.' },
        { cs: ['Vyhledej podporu (studijní poradce, psycholog)', 'Zkus techniku 4-7-8 dýchání před spaním', 'Rozděl zkoušky do menších bloků přípravy'], en: ['Seek support (study advisor, psychologist)', 'Try 4-7-8 breathing technique before sleep', 'Break exam prep into smaller blocks'] }),
      studyStrategies: ar(69, { cs: 'Dobré studijní strategie', en: 'Good Study Strategies' },
        { cs: 'Máš solidní základ, ale je prostor pro zlepšení.', en: 'You have a solid foundation but room for improvement.' },
        { cs: ['Přidej active recall – testuj se místo opakovaného čtení', 'Zkus Pomodoro techniku (25 min práce, 5 min pauza)', 'Používej Anki nebo Quizlet pro spaced repetition'], en: ['Add active recall – test yourself instead of re-reading', 'Try Pomodoro technique (25 min work, 5 min break)', 'Use Anki or Quizlet for spaced repetition'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 3, percent: 38, description: { cs: 'Preferuješ klid a samostatnou práci.', en: 'You prefer quiet and independent work.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 5, percent: 63, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 8, percent: 100, description: { cs: 'Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'You are organized, reliable, and goal-oriented.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 2, percent: 25, description: { cs: 'Jsi citlivý/á a emoce prožíváš intenzivně.', en: 'You are sensitive and experience emotions intensely.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 4, percent: 50, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Svědomitost. Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'Your most prominent trait is Conscientiousness. You are organized, reliable, and goal-oriented.' },
      },
      vak: { visual: 40, auditory: 40, kinesthetic: 20, label: 'Vizuální-Auditivní mix' },
    },
  },

  // ──────────────────────────────────────────────
  // 7. Eliška Horáková – Self-directed learner
  // ──────────────────────────────────────────────
  {
    name: 'Eliška Horáková',
    description: {
      cs: 'Samostatná studentka s vysokou metakognicí a růstovým myšlením, ale introvertní.',
      en: 'Independent student with high metacognition and growth mindset, but introverted.',
    },
    results: {
      growthMindset: ar(88, { cs: 'Silné růstové myšlení', en: 'Strong Growth Mindset' },
        { cs: 'Věříš, že schopnosti lze rozvíjet úsilím a učením.', en: 'You believe abilities can be developed through effort and learning.' },
        { cs: ['Pokračuj v přijímání výzev', 'Pomáhej ostatním rozvíjet růstové myšlení', 'Sdílej své strategie učení'], en: ['Continue embracing challenges', 'Help others develop growth mindset', 'Share your learning strategies'] }),
      grit: ar(81, { cs: 'Vysoká vytrvalost (Grit)', en: 'High Grit' },
        { cs: 'Máš silnou vytrvalost a schopnost dotahovat věci do konce.', en: 'You have strong perseverance and ability to see things through.' },
        { cs: ['Využij svou vytrvalost pro náročné dlouhodobé cíle', 'Pomáhej ostatním s motivací', 'Hledej mentory pro další růst'], en: ['Use your grit for challenging long-term goals', 'Help others with motivation', 'Seek mentors for further growth'] }),
      selfEfficacy: ar(78, { cs: 'Vysoká self-efficacy', en: 'High Self-Efficacy' },
        { cs: 'Silně věříš ve své schopnosti a zvládání výzev.', en: 'You strongly believe in your abilities and handling challenges.' },
        { cs: ['Přijímej náročnější výzvy', 'Buď mentorem pro ostatní', 'Stanovuj si ambiciózní cíle'], en: ['Take on more challenging goals', 'Be a mentor to others', 'Set ambitious goals'] }),
      testAnxiety: ar(69, { cs: 'Mírná testová úzkost', en: 'Mild Test Anxiety' },
        { cs: 'Občas cítíš stres před zkouškami.', en: 'You sometimes feel stressed before exams.' },
        { cs: ['Nauč se dechová cvičení', 'Připravuj se s dostatečným předstihem', 'Vyzkoušej progresivní svalovou relaxaci'], en: ['Learn breathing exercises', 'Prepare well in advance', 'Try progressive muscle relaxation'] }),
      metacognition: ar(91, { cs: 'Vysoká metakognice', en: 'High Metacognition' },
        { cs: 'Dobře znáš své myšlení a umíš se efektivně učit.', en: 'You know your thinking well and learn effectively.' },
        { cs: ['Sdílej své strategie s ostatními', 'Zkoušej pokročilé techniky učení', 'Pomáhej spolužákům'], en: ['Share your strategies with others', 'Try advanced learning techniques', 'Help classmates'] }),
      eq: ar(59, { cs: 'Dobrá emoční inteligence', en: 'Good Emotional Intelligence' },
        { cs: 'Většinou rozumíš emocím a dokážeš je zvládat.', en: 'You usually understand emotions and can manage them.' },
        { cs: ['Rozvíjej aktivní naslouchání', 'Praktikuj empatii v každodenních situacích', 'Nauč se rozpoznávat emoce u druhých'], en: ['Develop active listening', 'Practice empathy in daily situations', 'Learn to recognize emotions in others'] }),
      procrastination: ar(78, { cs: 'Nízká prokrastinace', en: 'Low Procrastination' },
        { cs: 'Málokdy odkládáš úkoly a máš dobré pracovní návyky.', en: 'You rarely put off tasks and have good work habits.' },
        { cs: ['Udržuj své návyky', 'Pomáhej ostatním s organizací', 'Využij volný čas pro rozvoj'], en: ['Maintain your habits', 'Help others with organization', 'Use free time for growth'] }),
      academicMotivation: ar(84, { cs: 'Silná vnitřní motivace', en: 'Strong Intrinsic Motivation' },
        { cs: 'Studuješ hlavně proto, že tě to baví a chceš se rozvíjet.', en: 'You study mainly because you enjoy it and want to develop.' },
        { cs: ['Hledej náročnější výzvy', 'Zapoj se do výzkumu nebo projektů', 'Sdílej své nadšení s ostatními'], en: ['Seek more challenging projects', 'Get involved in research or projects', 'Share your enthusiasm with others'] }),
      timeManagement: ar(78, { cs: 'Výborný time management', en: 'Excellent Time Management' },
        { cs: 'Výborně si organizuješ čas a plníš termíny.', en: 'You organize your time excellently and meet deadlines.' },
        { cs: ['Zkus pokročilé techniky jako time blocking', 'Pomáhej ostatním s plánováním', 'Optimalizuj své rutiny'], en: ['Try advanced techniques like time blocking', 'Help others with planning', 'Optimize your routines'] }),
      locusOfControl: ar(88, { cs: 'Silný interní locus of control', en: 'Strong Internal Locus of Control' },
        { cs: 'Věříš, že tvé výsledky závisí hlavně na tvém úsilí.', en: 'You believe your results depend mainly on your effort.' },
        { cs: ['Využij svou zodpovědnost pro větší cíle', 'Inspiruj ostatní svým přístupem', 'Hledej oblasti, kde můžeš mít ještě větší vliv'], en: ['Use your responsibility for bigger goals', 'Inspire others with your approach', 'Find areas where you can have even greater impact'] }),
      resilience: ar(75, { cs: 'Vysoká resilience', en: 'High Resilience' },
        { cs: 'Dokážeš se rychle vzpamatovat z neúspěchů a adaptovat se.', en: 'You can quickly recover from setbacks and adapt.' },
        { cs: ['Pomáhej ostatním budovat odolnost', 'Přijímej větší výzvy', 'Sdílej své copingové strategie'], en: ['Help others build resilience', 'Take on bigger challenges', 'Share your coping strategies'] }),
      studyStress: ar(72, { cs: 'Mírný studijní stres', en: 'Moderate Study Stress' },
        { cs: 'Občas cítíš stres, ale většinou ho zvládáš.', en: 'You sometimes feel stressed but usually manage it.' },
        { cs: ['Zaveď pravidelný pohyb (i 20 min denně pomůže)', 'Plánuj studium s přestávkami', 'Nauč se říkat ne nepodstatným aktivitám'], en: ['Start regular exercise (even 20 min daily helps)', 'Plan study sessions with breaks', 'Learn to say no to non-essential activities'] }),
      studyStrategies: ar(88, { cs: 'Pokročilé studijní strategie', en: 'Advanced Study Strategies' },
        { cs: 'Používáš evidence-based techniky učení. Tvůj přístup je vědecky efektivní.', en: 'You use evidence-based learning techniques. Your approach is scientifically effective.' },
        { cs: ['Zkus interleaving – střídej témata při učení', 'Sdílej strategie se spolužáky', 'Experimentuj s elaborative interrogation'], en: ['Try interleaving – alternate topics while studying', 'Share strategies with classmates', 'Experiment with elaborative interrogation'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 2, percent: 25, description: { cs: 'Preferuješ klid a samostatnou práci.', en: 'You prefer quiet and independent work.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 5, percent: 63, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 7, percent: 88, description: { cs: 'Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'You are organized, reliable, and goal-oriented.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 6, percent: 75, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 7, percent: 88, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Svědomitost. Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'Your most prominent trait is Conscientiousness. You are organized, reliable, and goal-oriented.' },
      },
      vak: { visual: 40, auditory: 15, kinesthetic: 45, label: 'Kinestetický preference' },
    },
  },

  // ──────────────────────────────────────────────
  // 8. David Kučera – Unmotivated but capable
  // ──────────────────────────────────────────────
  {
    name: 'David Kučera',
    description: {
      cs: 'Schopný student s vysokými kognitivními skóre, ale nízkou motivací a prokrastinací.',
      en: 'Capable student with high cognitive scores but low motivation and procrastination.',
    },
    results: {
      growthMindset: ar(66, { cs: 'Převážně růstové myšlení', en: 'Mostly Growth Mindset' },
        { cs: 'Většinou věříš v možnost rozvoje, ale někdy pochybuješ.', en: 'You mostly believe in development potential, but sometimes doubt.' },
        { cs: ['Všímej si svých fixních myšlenek', 'Přeformuluj "neumím to" na "zatím neumím"', 'Oceňuj proces, ne jen výsledek'], en: ['Notice your fixed mindset thoughts', 'Reframe "I can\'t" to "I can\'t yet"', 'Value the process, not just results'] }),
      grit: ar(38, { cs: 'Rozvíjející se vytrvalost', en: 'Developing Perseverance' },
        { cs: 'Máš tendenci měnit směr, ale můžeš to zlepšit.', en: 'You tend to change direction, but you can improve.' },
        { cs: ['Začni s kratšími projekty', 'Veď si deník pokroku', 'Najdi svou vášeň'], en: ['Start with shorter projects', 'Keep a progress journal', 'Find your passion'] }),
      selfEfficacy: ar(72, { cs: 'Dobrá self-efficacy', en: 'Good Self-Efficacy' },
        { cs: 'Věříš si ve většině situací.', en: 'You believe in yourself in most situations.' },
        { cs: ['Zaznamenávej své úspěchy', 'Vizualizuj úspěšné zvládnutí úkolů', 'Hledej pozitivní zpětnou vazbu'], en: ['Record your successes', 'Visualize successful task completion', 'Seek positive feedback'] }),
      testAnxiety: ar(72, { cs: 'Mírná testová úzkost', en: 'Mild Test Anxiety' },
        { cs: 'Občas cítíš stres před zkouškami.', en: 'You sometimes feel stressed before exams.' },
        { cs: ['Nauč se dechová cvičení', 'Připravuj se s dostatečným předstihem', 'Vyzkoušej progresivní svalovou relaxaci'], en: ['Learn breathing exercises', 'Prepare well in advance', 'Try progressive muscle relaxation'] }),
      metacognition: ar(75, { cs: 'Vysoká metakognice', en: 'High Metacognition' },
        { cs: 'Dobře znáš své myšlení a umíš se efektivně učit.', en: 'You know your thinking well and learn effectively.' },
        { cs: ['Sdílej své strategie s ostatními', 'Zkoušej pokročilé techniky učení', 'Pomáhej spolužákům'], en: ['Share your strategies with others', 'Try advanced learning techniques', 'Help classmates'] }),
      eq: ar(53, { cs: 'Dobrá emoční inteligence', en: 'Good Emotional Intelligence' },
        { cs: 'Většinou rozumíš emocím a dokážeš je zvládat.', en: 'You usually understand emotions and can manage them.' },
        { cs: ['Rozvíjej aktivní naslouchání', 'Praktikuj empatii v každodenních situacích', 'Nauč se rozpoznávat emoce u druhých'], en: ['Develop active listening', 'Practice empathy in daily situations', 'Learn to recognize emotions in others'] }),
      procrastination: ar(28, { cs: 'Vyšší prokrastinace', en: 'Moderate Procrastination' },
        { cs: 'Často odkládáš úkoly a necháváš věci na poslední chvíli.', en: 'You often put off tasks and leave things to the last minute.' },
        { cs: ['Rozděl velké úkoly na malé kroky (max 15 min)', 'Odstraň rozptýlení při práci', 'Nastav si pravidelné studijní bloky'], en: ['Break big tasks into small steps (max 15 min)', 'Remove distractions while working', 'Set regular study blocks'] }),
      academicMotivation: ar(31, { cs: 'Převážně vnější motivace', en: 'Mostly External Motivation' },
        { cs: 'Studuješ hlavně kvůli známkám, rodičům nebo titulu.', en: 'You study mainly for grades, parents, or a degree.' },
        { cs: ['Najdi osobní smysl v tom, co studuješ', 'Propoj studium s budoucí kariérou', 'Zkus hledat zajímavé aspekty i v nudných předmětech'], en: ['Find personal meaning in what you study', 'Connect studies with future career', 'Try to find interesting aspects even in boring subjects'] }),
      timeManagement: ar(34, { cs: 'Slabší time management', en: 'Weak Time Management' },
        { cs: 'Máš potíže s organizací času a plánováním.', en: 'You have trouble organizing your time and planning.' },
        { cs: ['Zkus si plánovat týden dopředu', 'Používej kalendář pro všechny termíny', 'Nastav si pevné studijní bloky'], en: ['Try planning a week ahead', 'Use a calendar for all deadlines', 'Set fixed study blocks'] }),
      locusOfControl: ar(59, { cs: 'Převážně interní locus', en: 'Mostly Internal Locus' },
        { cs: 'Většinou věříš, že máš vliv na své výsledky.', en: 'You mostly believe you have influence over your results.' },
        { cs: ['Posiluj přesvědčení, že tvé úsilí se vyplatí', 'Analyzuj své úspěchy – co jsi udělal/a správně?', 'Přijmi zodpovědnost za své výsledky'], en: ['Strengthen the belief that your effort pays off', 'Analyze your successes – what did you do right?', 'Accept responsibility for your results'] }),
      resilience: ar(59, { cs: 'Dobrá resilience', en: 'Good Resilience' },
        { cs: 'Většinou se dokážeš vzpamatovat z neúspěchů.', en: 'You can usually recover from setbacks.' },
        { cs: ['Buduj síť podpory', 'Praktikuj vděčnost', 'Hledej příležitosti v překážkách'], en: ['Build a support network', 'Practice gratitude', 'Look for opportunities in obstacles'] }),
      studyStress: ar(63, { cs: 'Mírný studijní stres', en: 'Moderate Study Stress' },
        { cs: 'Občas cítíš stres, ale většinou ho zvládáš.', en: 'You sometimes feel stressed but usually manage it.' },
        { cs: ['Zaveď pravidelný pohyb (i 20 min denně pomůže)', 'Plánuj studium s přestávkami', 'Nauč se říkat ne nepodstatným aktivitám'], en: ['Start regular exercise (even 20 min daily helps)', 'Plan study sessions with breaks', 'Learn to say no to non-essential activities'] }),
      studyStrategies: ar(63, { cs: 'Dobré studijní strategie', en: 'Good Study Strategies' },
        { cs: 'Máš solidní základ, ale je prostor pro zlepšení.', en: 'You have a solid foundation but room for improvement.' },
        { cs: ['Přidej active recall – testuj se místo opakovaného čtení', 'Zkus Pomodoro techniku (25 min práce, 5 min pauza)', 'Používej Anki nebo Quizlet pro spaced repetition'], en: ['Add active recall – test yourself instead of re-reading', 'Try Pomodoro technique (25 min work, 5 min break)', 'Use Anki or Quizlet for spaced repetition'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 5, percent: 63, description: { cs: 'Jsi společenský/á a energický/á v sociálních situacích.', en: 'You are sociable and energetic in social situations.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 4, percent: 50, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 3, percent: 38, description: { cs: 'Jsi flexibilní a spontánní, ale možná méně organizovaný/á.', en: 'You are flexible and spontaneous, but perhaps less organized.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 6, percent: 75, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 6, percent: 75, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Emoční stabilita. Jsi klidný/á a odolný/á vůči stresu.', en: 'Your most prominent trait is Emotional Stability. You are calm and resilient to stress.' },
      },
      vak: { visual: 35, auditory: 35, kinesthetic: 30, label: 'Vizuální-Auditivní mix' },
    },
  },

  // ──────────────────────────────────────────────
  // 9. Barbora Veselá – Resilient adapter
  // ──────────────────────────────────────────────
  {
    name: 'Barbora Veselá',
    description: {
      cs: 'Odolná studentka s dobrými copingovými strategiemi a vyrovnanými výsledky.',
      en: 'Resilient student with good coping strategies and balanced results.',
    },
    results: {
      growthMindset: ar(69, { cs: 'Převážně růstové myšlení', en: 'Mostly Growth Mindset' },
        { cs: 'Většinou věříš v možnost rozvoje, ale někdy pochybuješ.', en: 'You mostly believe in development potential, but sometimes doubt.' },
        { cs: ['Všímej si svých fixních myšlenek', 'Přeformuluj "neumím to" na "zatím neumím"', 'Oceňuj proces, ne jen výsledek'], en: ['Notice your fixed mindset thoughts', 'Reframe "I can\'t" to "I can\'t yet"', 'Value the process, not just results'] }),
      grit: ar(66, { cs: 'Dobrá vytrvalost', en: 'Good Perseverance' },
        { cs: 'Většinou dokážeš vytrvat, ale někdy se necháš odvést.', en: 'You can usually persevere, but sometimes get sidetracked.' },
        { cs: ['Rozděluj velké cíle na menší kroky', 'Najdi si accountability partnera', 'Slaví malé úspěchy'], en: ['Break big goals into smaller steps', 'Find an accountability partner', 'Celebrate small wins'] }),
      selfEfficacy: ar(63, { cs: 'Dobrá self-efficacy', en: 'Good Self-Efficacy' },
        { cs: 'Věříš si ve většině situací.', en: 'You believe in yourself in most situations.' },
        { cs: ['Zaznamenávej své úspěchy', 'Vizualizuj úspěšné zvládnutí úkolů', 'Hledej pozitivní zpětnou vazbu'], en: ['Record your successes', 'Visualize successful task completion', 'Seek positive feedback'] }),
      testAnxiety: ar(63, { cs: 'Mírná testová úzkost', en: 'Mild Test Anxiety' },
        { cs: 'Občas cítíš stres před zkouškami.', en: 'You sometimes feel stressed before exams.' },
        { cs: ['Nauč se dechová cvičení', 'Připravuj se s dostatečným předstihem', 'Vyzkoušej progresivní svalovou relaxaci'], en: ['Learn breathing exercises', 'Prepare well in advance', 'Try progressive muscle relaxation'] }),
      metacognition: ar(63, { cs: 'Dobrá metakognice', en: 'Good Metacognition' },
        { cs: 'Většinou si uvědomuješ své učení.', en: 'You\'re usually aware of your learning.' },
        { cs: ['Veď si učební deník', 'Experimentuj s novými technikami', 'Ptej se sám sebe "proč?"'], en: ['Keep a learning journal', 'Experiment with new techniques', 'Ask yourself "why?"'] }),
      eq: ar(72, { cs: 'Dobrá emoční inteligence', en: 'Good Emotional Intelligence' },
        { cs: 'Většinou rozumíš emocím a dokážeš je zvládat.', en: 'You usually understand emotions and can manage them.' },
        { cs: ['Rozvíjej aktivní naslouchání', 'Praktikuj empatii v každodenních situacích', 'Nauč se rozpoznávat emoce u druhých'], en: ['Develop active listening', 'Practice empathy in daily situations', 'Learn to recognize emotions in others'] }),
      procrastination: ar(63, { cs: 'Mírná prokrastinace', en: 'Mild Procrastination' },
        { cs: 'Občas odkládáš úkoly, ale většinou je zvládneš včas.', en: 'You sometimes put off tasks, but usually manage them on time.' },
        { cs: ['Začni s nejtěžším úkolem ráno', 'Používej techniku „eat the frog"', 'Nastav si krátké deadliny pro dílčí kroky'], en: ['Start with the hardest task in the morning', 'Use the "eat the frog" technique', 'Set short deadlines for sub-tasks'] }),
      academicMotivation: ar(63, { cs: 'Smíšená motivace', en: 'Mixed Motivation' },
        { cs: 'Motivace závisí na předmětu – některé tě baví, jiné ne.', en: 'Your motivation depends on the subject – you enjoy some, not others.' },
        { cs: ['Hledej propojení mezi předměty a svými zájmy', 'Zkus kreativní přístup i k nudným předmětům', 'Stanovi si osobní cíle pro každý předmět'], en: ['Find connections between subjects and your interests', 'Try a creative approach even for boring subjects', 'Set personal goals for each subject'] }),
      timeManagement: ar(59, { cs: 'Dobrý time management', en: 'Good Time Management' },
        { cs: 'Většinou si dobře organizuješ čas.', en: 'You usually organize your time well.' },
        { cs: ['Zkus Pomodoro techniku', 'Optimalizuj své ranní rutiny', 'Plánuj s ohledem na svou energii'], en: ['Try the Pomodoro technique', 'Optimize your morning routines', 'Plan according to your energy levels'] }),
      locusOfControl: ar(69, { cs: 'Převážně interní locus', en: 'Mostly Internal Locus' },
        { cs: 'Většinou věříš, že máš vliv na své výsledky.', en: 'You mostly believe you have influence over your results.' },
        { cs: ['Posiluj přesvědčení, že tvé úsilí se vyplatí', 'Analyzuj své úspěchy – co jsi udělal/a správně?', 'Přijmi zodpovědnost za své výsledky'], en: ['Strengthen the belief that your effort pays off', 'Analyze your successes – what did you do right?', 'Accept responsibility for your results'] }),
      resilience: ar(81, { cs: 'Vysoká resilience', en: 'High Resilience' },
        { cs: 'Dokážeš se rychle vzpamatovat z neúspěchů a adaptovat se.', en: 'You can quickly recover from setbacks and adapt.' },
        { cs: ['Pomáhej ostatním budovat odolnost', 'Přijímej větší výzvy', 'Sdílej své copingové strategie'], en: ['Help others build resilience', 'Take on bigger challenges', 'Share your coping strategies'] }),
      studyStress: ar(72, { cs: 'Mírný studijní stres', en: 'Moderate Study Stress' },
        { cs: 'Občas cítíš stres, ale většinou ho zvládáš.', en: 'You sometimes feel stressed but usually manage it.' },
        { cs: ['Zaveď pravidelný pohyb (i 20 min denně pomůže)', 'Plánuj studium s přestávkami', 'Nauč se říkat ne nepodstatným aktivitám'], en: ['Start regular exercise (even 20 min daily helps)', 'Plan study sessions with breaks', 'Learn to say no to non-essential activities'] }),
      studyStrategies: ar(59, { cs: 'Dobré studijní strategie', en: 'Good Study Strategies' },
        { cs: 'Máš solidní základ, ale je prostor pro zlepšení.', en: 'You have a solid foundation but room for improvement.' },
        { cs: ['Přidej active recall – testuj se místo opakovaného čtení', 'Zkus Pomodoro techniku (25 min práce, 5 min pauza)', 'Používej Anki nebo Quizlet pro spaced repetition'], en: ['Add active recall – test yourself instead of re-reading', 'Try Pomodoro technique (25 min work, 5 min break)', 'Use Anki or Quizlet for spaced repetition'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 5, percent: 63, description: { cs: 'Jsi společenský/á a energický/á v sociálních situacích.', en: 'You are sociable and energetic in social situations.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 6, percent: 75, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 5, percent: 63, description: { cs: 'Jsi organizovaný/á, spolehlivý/á a cílevědomý/á.', en: 'You are organized, reliable, and goal-oriented.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 6, percent: 75, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 5, percent: 63, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Přívětivost. Jsi vstřícný/á, empatický/á a kooperativní.', en: 'Your most prominent trait is Agreeableness. You are warm, empathetic, and cooperative.' },
      },
      vak: { visual: 35, auditory: 30, kinesthetic: 35, label: 'Vyvážený' },
    },
  },

  // ──────────────────────────────────────────────
  // 10. Ondřej Šťastný – Fresh start (typical first-year)
  // ──────────────────────────────────────────────
  {
    name: 'Ondřej Šťastný',
    description: {
      cs: 'Typický prvák s velmi smíšenými výsledky – hledá svou cestu na vysoké škole.',
      en: 'Typical first-year student with very mixed results – finding his way at university.',
    },
    results: {
      growthMindset: ar(50, { cs: 'Převážně růstové myšlení', en: 'Mostly Growth Mindset' },
        { cs: 'Většinou věříš v možnost rozvoje, ale někdy pochybuješ.', en: 'You mostly believe in development potential, but sometimes doubt.' },
        { cs: ['Všímej si svých fixních myšlenek', 'Přeformuluj "neumím to" na "zatím neumím"', 'Oceňuj proces, ne jen výsledek'], en: ['Notice your fixed mindset thoughts', 'Reframe "I can\'t" to "I can\'t yet"', 'Value the process, not just results'] }),
      grit: ar(47, { cs: 'Rozvíjející se vytrvalost', en: 'Developing Perseverance' },
        { cs: 'Máš tendenci měnit směr, ale můžeš to zlepšit.', en: 'You tend to change direction, but you can improve.' },
        { cs: ['Začni s kratšími projekty', 'Veď si deník pokroku', 'Najdi svou vášeň'], en: ['Start with shorter projects', 'Keep a progress journal', 'Find your passion'] }),
      selfEfficacy: ar(44, { cs: 'Střední self-efficacy', en: 'Moderate Self-Efficacy' },
        { cs: 'Občas pochybuješ o svých schopnostech.', en: 'You sometimes doubt your abilities.' },
        { cs: ['Začni s menšími úkoly a postupně zvyšuj', 'Najdi vzory, které tě inspirují', 'Pracuj na pozitivním self-talku'], en: ['Start with smaller tasks and gradually increase', 'Find role models who inspire you', 'Work on positive self-talk'] }),
      testAnxiety: ar(44, { cs: 'Mírná testová úzkost', en: 'Mild Test Anxiety' },
        { cs: 'Občas cítíš stres před zkouškami.', en: 'You sometimes feel stressed before exams.' },
        { cs: ['Nauč se dechová cvičení', 'Připravuj se s dostatečným předstihem', 'Vyzkoušej progresivní svalovou relaxaci'], en: ['Learn breathing exercises', 'Prepare well in advance', 'Try progressive muscle relaxation'] }),
      metacognition: ar(41, { cs: 'Rozvíjející se metakognice', en: 'Developing Metacognition' },
        { cs: 'Začínáš si uvědomovat důležitost plánování učení.', en: 'You\'re beginning to realize the importance of planning your learning.' },
        { cs: ['Před učením si napiš 3 otázky, na které chceš znát odpověď', 'Po učení si řekni nahlas, co sis zapamatoval/a', 'Zkus Pomodoro techniku'], en: ['Before studying, write 3 questions you want answered', 'After studying, say aloud what you remember', 'Try the Pomodoro technique'] }),
      eq: ar(50, { cs: 'Dobrá emoční inteligence', en: 'Good Emotional Intelligence' },
        { cs: 'Většinou rozumíš emocím a dokážeš je zvládat.', en: 'You usually understand emotions and can manage them.' },
        { cs: ['Rozvíjej aktivní naslouchání', 'Praktikuj empatii v každodenních situacích', 'Nauč se rozpoznávat emoce u druhých'], en: ['Develop active listening', 'Practice empathy in daily situations', 'Learn to recognize emotions in others'] }),
      procrastination: ar(41, { cs: 'Mírná prokrastinace', en: 'Mild Procrastination' },
        { cs: 'Občas odkládáš úkoly, ale většinou je zvládneš včas.', en: 'You sometimes put off tasks, but usually manage them on time.' },
        { cs: ['Začni s nejtěžším úkolem ráno', 'Používej techniku „eat the frog"', 'Nastav si krátké deadliny pro dílčí kroky'], en: ['Start with the hardest task in the morning', 'Use the "eat the frog" technique', 'Set short deadlines for sub-tasks'] }),
      academicMotivation: ar(50, { cs: 'Smíšená motivace', en: 'Mixed Motivation' },
        { cs: 'Motivace závisí na předmětu – některé tě baví, jiné ne.', en: 'Your motivation depends on the subject – you enjoy some, not others.' },
        { cs: ['Hledej propojení mezi předměty a svými zájmy', 'Zkus kreativní přístup i k nudným předmětům', 'Stanovi si osobní cíle pro každý předmět'], en: ['Find connections between subjects and your interests', 'Try a creative approach even for boring subjects', 'Set personal goals for each subject'] }),
      timeManagement: ar(44, { cs: 'Slabší time management', en: 'Weak Time Management' },
        { cs: 'Máš potíže s organizací času a plánováním.', en: 'You have trouble organizing your time and planning.' },
        { cs: ['Zkus si plánovat týden dopředu', 'Používej kalendář pro všechny termíny', 'Nastav si pevné studijní bloky'], en: ['Try planning a week ahead', 'Use a calendar for all deadlines', 'Set fixed study blocks'] }),
      locusOfControl: ar(50, { cs: 'Převážně interní locus', en: 'Mostly Internal Locus' },
        { cs: 'Většinou věříš, že máš vliv na své výsledky.', en: 'You mostly believe you have influence over your results.' },
        { cs: ['Posiluj přesvědčení, že tvé úsilí se vyplatí', 'Analyzuj své úspěchy – co jsi udělal/a správně?', 'Přijmi zodpovědnost za své výsledky'], en: ['Strengthen the belief that your effort pays off', 'Analyze your successes – what did you do right?', 'Accept responsibility for your results'] }),
      resilience: ar(50, { cs: 'Dobrá resilience', en: 'Good Resilience' },
        { cs: 'Většinou se dokážeš vzpamatovat z neúspěchů.', en: 'You can usually recover from setbacks.' },
        { cs: ['Buduj síť podpory', 'Praktikuj vděčnost', 'Hledej příležitosti v překážkách'], en: ['Build a support network', 'Practice gratitude', 'Look for opportunities in obstacles'] }),
      studyStress: ar(47, { cs: 'Mírný studijní stres', en: 'Moderate Study Stress' },
        { cs: 'Občas cítíš stres, ale většinou ho zvládáš.', en: 'You sometimes feel stressed but usually manage it.' },
        { cs: ['Zaveď pravidelný pohyb (i 20 min denně pomůže)', 'Plánuj studium s přestávkami', 'Nauč se říkat ne nepodstatným aktivitám'], en: ['Start regular exercise (even 20 min daily helps)', 'Plan study sessions with breaks', 'Learn to say no to non-essential activities'] }),
      studyStrategies: ar(38, { cs: 'Základní studijní strategie', en: 'Basic Study Strategies' },
        { cs: 'Tvé učební strategie nejsou moc efektivní. Malé změny mohou přinést velký rozdíl.', en: 'Your learning strategies aren\'t very effective. Small changes can make a big difference.' },
        { cs: ['Přestaň jen číst – začni se testovat (active recall)', 'Najdi si tiché místo na učení', 'Dělej si poznámky vlastními slovy, ne opisuj'], en: ['Stop just reading – start testing yourself (active recall)', 'Find a quiet study place', 'Take notes in your own words, don\'t just copy'] }),
      bigFive: {
        dimensions: [
          { name: { cs: 'Extraverze', en: 'Extraversion' }, score: 5, percent: 63, description: { cs: 'Jsi společenský/á a energický/á v sociálních situacích.', en: 'You are sociable and energetic in social situations.' } },
          { name: { cs: 'Přívětivost', en: 'Agreeableness' }, score: 5, percent: 63, description: { cs: 'Jsi vstřícný/á, empatický/á a kooperativní.', en: 'You are warm, empathetic, and cooperative.' } },
          { name: { cs: 'Svědomitost', en: 'Conscientiousness' }, score: 3, percent: 38, description: { cs: 'Jsi flexibilní a spontánní, ale možná méně organizovaný/á.', en: 'You are flexible and spontaneous, but perhaps less organized.' } },
          { name: { cs: 'Emoční stabilita', en: 'Emotional Stability' }, score: 4, percent: 50, description: { cs: 'Jsi klidný/á a odolný/á vůči stresu.', en: 'You are calm and resilient to stress.' } },
          { name: { cs: 'Otevřenost zkušenosti', en: 'Openness to Experience' }, score: 5, percent: 63, description: { cs: 'Jsi kreativní, zvídavý/á a otevřený/á novinkám.', en: 'You are creative, curious, and open to new things.' } },
        ],
        summary: { cs: 'Tvůj nejvýraznější rys je Extraverze. Jsi společenský/á a energický/á v sociálních situacích.', en: 'Your most prominent trait is Extraversion. You are sociable and energetic in social situations.' },
      },
      vak: { visual: 30, auditory: 40, kinesthetic: 30, label: 'Auditivní preference' },
    },
  },
];
